<?xml version="1.0" encoding="utf-8"?><Database Name="gestion_des_produits" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=gestion_des_produits;Integrated Security=True" SettingsObjectName="gestion_des_etreprises.Properties.Settings" SettingsPropertyName="gestion_des_produitsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Achate" Member="Achate">
    <Type Name="Achate">
      <Column Name="NumAchate" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumProduit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumVendeur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantitéProduit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateAchate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="commenter" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="prixAchate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="payment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Vendeur_Achate" Member="Vendeur" ThisKey="NumVendeur" OtherKey="NumVendeur" Type="Vendeur" IsForeignKey="true" />
      <Association Name="Vendeur_Achate1" Member="Vendeur1" ThisKey="NumVendeur" OtherKey="NumVendeur" Type="Vendeur" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Produit_Achate" Member="Produit" ThisKey="NumProduit" OtherKey="NumProduit" Type="Produit" IsForeignKey="true" />
      <Association Name="Produit_Achate1" Member="Produit1" ThisKey="NumProduit" OtherKey="NumProduit" Type="Produit" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fournisseur" Member="Fournisseur">
    <Type Name="Fournisseur">
      <Column Name="NumFournisseur" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameFournisseur" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TelFournisseur" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddressFournisseur" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Fournisseur_Produit" Member="Produit" ThisKey="NumFournisseur" OtherKey="NumFournisseur" Type="Produit" />
    </Type>
  </Table>
  <Table Name="dbo.Vendeur" Member="Vendeur">
    <Type Name="Vendeur">
      <Column Name="NumVendeur" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameVendeur" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Vendeur_Achate" Member="Achate" ThisKey="NumVendeur" OtherKey="NumVendeur" Type="Achate" />
      <Association Name="Vendeur_Achate1" Member="Achate1" ThisKey="NumVendeur" OtherKey="NumVendeur" Type="Achate" />
    </Type>
  </Table>
  <Table Name="dbo.Produit" Member="Produit">
    <Type Name="Produit">
      <Column Name="NumProduit" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumFournisseur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nameProduit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="quantité" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeProduit" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="prix_Fournisseur" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="prix_achat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DateCommande" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="payment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Produit_Achate" Member="Achate" ThisKey="NumProduit" OtherKey="NumProduit" Type="Achate" />
      <Association Name="Produit_Achate1" Member="Achate1" ThisKey="NumProduit" OtherKey="NumProduit" Type="Achate" />
      <Association Name="Fournisseur_Produit" Member="Fournisseur" ThisKey="NumFournisseur" OtherKey="NumFournisseur" Type="Fournisseur" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reparation" Member="Reparation">
    <Type Name="Reparation">
      <Column Name="Num_Reparation" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titre_Reparation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Prix" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Reparation" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Telephone_Client" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Commenter" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="payment" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>